export enum ApiErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  RATE_LIMITED = "RATE_LIMITED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
  INVALID_CURRENCY = "INVALID_CURRENCY",
  INVALID_AMOUNT = "INVALID_AMOUNT",
  OWNERSHIP_ERROR = "OWNERSHIP_ERROR",
}
