namespace AuthNexus.Modules.Audit;

public enum SecurityEventType
{
    RegistrationRequested = 1,
    RegistrationCompleted = 2,
    EmailVerificationSent = 3,
    EmailVerified = 4,
    PhoneVerificationSent = 5,
    PhoneVerified = 6,
    LoginSucceeded = 7,
    LoginFailed = 8,
    LoginThrottled = 9,
    MfaRequired = 10,
    MfaSucceeded = 11,
    MfaFailed = 12,
    PasswordResetRequested = 13,
    PasswordResetCompleted = 14,
    PasswordChanged = 15,
    PasskeyAdded = 16,
    PasskeyUsed = 17,
    PasskeyRemoved = 18,
    TotpAdded = 19,
    TotpRemoved = 20,
    RecoveryCodeUsed = 21,
    ExternalIdentityLinked = 22,
    ExternalIdentityUnlinked = 23,
    SessionCreated = 24,
    SessionRevoked = 25,
    LogoutAll = 26,
    SecurityStepUpRequired = 27,
    SecurityStepUpCompleted = 28,
    AccountTemporarilyProtected = 29,
    AccountSuspended = 30,
    AccountDeletionRequested = 31,
    AccountDeleted = 32,
    AuthorizationDenied = 33,
    PolicyDraftCreated = 34,
    PolicyChanged = 35,
    PolicyApproved = 36,
    ProviderUnavailable = 37,
}

public static class SecurityEventTypeExtensions
{
    public static string ToCode(this SecurityEventType eventType) =>
        eventType switch
        {
            SecurityEventType.RegistrationRequested => "registration_requested",
            SecurityEventType.RegistrationCompleted => "registration_completed",
            SecurityEventType.EmailVerificationSent => "email_verification_sent",
            SecurityEventType.EmailVerified => "email_verified",
            SecurityEventType.PhoneVerificationSent => "phone_verification_sent",
            SecurityEventType.PhoneVerified => "phone_verified",
            SecurityEventType.LoginSucceeded => "login_succeeded",
            SecurityEventType.LoginFailed => "login_failed",
            SecurityEventType.LoginThrottled => "login_throttled",
            SecurityEventType.MfaRequired => "mfa_required",
            SecurityEventType.MfaSucceeded => "mfa_succeeded",
            SecurityEventType.MfaFailed => "mfa_failed",
            SecurityEventType.PasswordResetRequested => "password_reset_requested",
            SecurityEventType.PasswordResetCompleted => "password_reset_completed",
            SecurityEventType.PasswordChanged => "password_changed",
            SecurityEventType.PasskeyAdded => "passkey_added",
            SecurityEventType.PasskeyUsed => "passkey_used",
            SecurityEventType.PasskeyRemoved => "passkey_removed",
            SecurityEventType.TotpAdded => "totp_added",
            SecurityEventType.TotpRemoved => "totp_removed",
            SecurityEventType.RecoveryCodeUsed => "recovery_code_used",
            SecurityEventType.ExternalIdentityLinked => "external_identity_linked",
            SecurityEventType.ExternalIdentityUnlinked => "external_identity_unlinked",
            SecurityEventType.SessionCreated => "session_created",
            SecurityEventType.SessionRevoked => "session_revoked",
            SecurityEventType.LogoutAll => "logout_all",
            SecurityEventType.SecurityStepUpRequired => "security_step_up_required",
            SecurityEventType.SecurityStepUpCompleted => "security_step_up_completed",
            SecurityEventType.AccountTemporarilyProtected => "account_temporarily_protected",
            SecurityEventType.AccountSuspended => "account_suspended",
            SecurityEventType.AccountDeletionRequested => "account_deletion_requested",
            SecurityEventType.AccountDeleted => "account_deleted",
            SecurityEventType.AuthorizationDenied => "authorization_denied",
            SecurityEventType.PolicyDraftCreated => "policy_draft_created",
            SecurityEventType.PolicyChanged => "policy_changed",
            SecurityEventType.PolicyApproved => "policy_approved",
            SecurityEventType.ProviderUnavailable => "provider_unavailable",
            _ => throw new ArgumentOutOfRangeException(
                nameof(eventType),
                eventType,
                "The security event type is not defined."),
        };
}
